# 本番用もとりあえずH2DBにしておく
spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2.console:
    enabled: true
    path: /h2-console

  jpa:
    database: H2
    hibernate.ddl-auto: update

azure.activedirectory.tenant-id: "xxx"
spring.security.oauth2.client.registration.azure.client-id: "xxx"
spring.security.oauth2.client.registration.azure.client-secret: "xxx"
azure.activedirectory.active-directory-groups: Users