# 本番用もとりあえずH2DBにしておく
spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2.console:
    enabled: true
    path: /h2-console

  jpa:
    database: H2
    hibernate.ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          azure:
            # Specifies your App Registration's Application ID:
            client-id: "xxx"
            # Specifies your App Registration's secret key:
            client-secret: "xxx"

# OAuth2設定
azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: "xxx"
    # Specifies the list of Active Directory groups to use for authorization:
    active-directory-groups: Users
